version: 1
accounts:
- name: EnLedgerCorp
  coins:
  - 10000000eecoin
  - 100energystake
  - 100energyasset_a1
  - 100multifamily_a1
  - 100commercial_a1
  - 100vacationlux_a1
- name: Dodecahedron
  coins:
  - 10000eecoin
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: Dodecahedron
  coins:
  - 1eecoin
validators:
- name: EnLedgerCorp
  bonded: 100energystake
